mate-academy/jv-program-common-mistakes

- assets/css/style.scss
> removed head link from each page

- java-core/builder-file/work-with-file.md
added one more point about nested connection to resource (work with file task)
> work with csv file checklist fix 

- hibernate/add-user-service/add-user-service-checklist.md
Added common mistakes to hibernate hw-6 (transaction isolation level topic: add user service task)
> added common mistakes to hibernate hw-6 (user service)

- hibernate/configuration/configuration_checklist.md
Add point about code duplication, removed exclamation marks since they are not visible from github.io
> Checklist update

- hibernate/criteria-query/criteria_query_checklist.md
> code view fix

- java-spring/rest/jv-spring-rest_checklist.md
Работает все без [аннотаций](https://www.baeldung.com/spring-autowired-abstract-class#constructor-injection)
> deleted point about abstract DAO

- java-spring/intro/java-spring-intro.md
> fixed spring intro checklist

- hibernate/configuration/configuration_checklist.md
> updated hibernate configuration checklist

- java-spring/rest-practice/jv-spring-rest-practice_checklist.md
> [Spring rest practice checklist]: added info about dtos and http methods

- java-core/abstract-class-interface/oop-advanced.md
> [OOP-advanced]: add point to checklist

- java-core/builder-file/read-from-file.md
> [Read from file]: add point System.lineSeparator()

- java-spring/security/jv-spring-security-checklist.md
> [Spring security]: clarification of remark about @Autowired

- hibernate/add-shopping-cart/add-shopping-cart-hw.md
> [Implement shopping cart]: delete point about fetch join user

- java-core/builder-file/work-with-file.md
> add point about imports

- java-core/dependency-injection/dependency-injection.md
Add point about adding exception object from catch to thrown exception
> [Checklist-fix]: add point about adding exception object

- java-web/web-security/java-web-security.md
Fuckup fix
* Добавить в чеклист как должен выглядеть endpoint для страницы для получения списка машин определенного водителя
* Удалить пункт чеклиста LINK
> removed redundant point and added example of endpoint naming

- hibernate/add-user-service/add-user-service-checklist.md
- hibernate/cascades/cascades_checklist.md
- java-spring/rest/jv-spring-rest_checklist.md
> Fix checklists

- project/clean_up_taxi_service.md
> added three new paragraphs to clean_up_taxi_service.md

- java-spring/rest-practice/jv-spring-rest-practice_checklist.md
> add paragraph about mapper interfaces

- java-core/junit/registration-validation.md
Added paragraph to registration-validation about splitting of big if into several small ones
Fuckup -> https://app.clickup.com/t/37whtba
> add paragraph to registration-validation

- java-JDBC/dao-vs-service/dao-vs-service_checklist.md
Fuckup -> https://app.clickup.com/t/2tk1pet
> replace find with get

- java-core/oop/lottery.md
Added two new paragraphs:
- using of name() method of enum instead of toString() and String.valueOf()
- magic numbers
Fuckup -> https://app.clickup.com/t/3bf5wp3
> add two paragraphs to lottery

- java-web/web-practice/java-web-practice.md
https://app.clickup.com/t/2rgq2px
> [java-web]: remove redundant quotation marks from common mistakes

- java-core/dependency-injection/dependency-injection.md
> remove duplicate paragraph in Dependency Injection checklist

- project/clean_up_taxi_service.md
Common mistake. Also, we need to check JDBC homework assignments and fix the same there.
> [taxi-serivce project]: add point about query and statement variable naming

- java-JDBC/jdbc-intro/JDBC-intro_checklist.md
Fixed typo in JDBC intro checklist
> Fixed typo in JDBC intro checklist

- java-core/junit/registration-validation.md
Was done according to [this](https://docs.google.com/document/d/1PS-JSbxMZUMSpK0dnz8WdVK5FOBd4wMETKdaxrzGFUA/edit) docs task
* added point about non-future-proof checks and requirements
* fixed and clarified mock user test data point
* fixed code examples
> Registration validation improvement
